version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins-docker
    build:
      context: .
    ports:
    - 8082:8080
    volumes:
    - ${HOME}/jenkins/pipeline/jenkins-data:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - net
networks:
  net:
