version: "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
    - 8080:8080
    volumes:
    - ${HOME}/jenkins/jenkins-data:/var/jenkins_home
    networks:
    - net
  remote_host:
    container_name: remote-host
    image: docker-host
    volumes:
      - ${HOME}/jenkins/installation/aws-s3.sh:/tmp/aws-s3.sh
    build:
      context: .
    networks:
    - net
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - ${HOME}/jenkins/db_data:/var/lib/mysql
    networks:
    - net
networks:
  net:
