version: 3
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
    - 8080:8080
    volumes:
    - ${HOME}/jenkins/jenkins-data:/var/jenkins_home
    network:
    - net
networks:
  net:
